- name: join master node
  block:
  - shell: "kubeadm join {{master_endpoint}} --token {{token}} --certificate-key {{certificate_key}} --discovery-token-unsafe-skip-ca-verification "
    register: kubeadm_master_node
  - debug: msg="{{kubeadm_master_node}}"
    when: debug is defined
  when: inventory_hostname != groups.master.0 and join is defined

- name: Install cilium
  block:
  - uri:
      url: "https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt"
      return_content: yes
    register: cilium_version
  - unarchive:
     src: "https://github.com/cilium/cilium-cli/releases/download/{{cilium_version.content|trim}}/cilium-linux-amd64.tar.gz"
     dest: /usr/local/bin
     remote_src: yes
  - shell: "KUBECONFIG=/etc/kubernetes/admin.conf cilium install"
    register: cilium_output
  - debug: msg="{{cilium_output}}"
    when: debug is defined
  when: cilium is defined

