- name: join master node
  block:
  - shell: "kubeadm join {{master_endpoint}} --token {{token}} --certificate-key {{certificate_key}} --discovery-token-unsafe-skip-ca-verification"
    register: kubeadm_master_node
  - debug: msg="{{kubeadm_master_node}}"
    when: debug is defined
  when: inventory_hostname != groups.master.0 and join is defined
  