---
# - debug: msg="{{lookup('fileglob', 'k8s.conf')}}"
- name: "setup autoload kernel modules"
  copy:
    src: "{{lookup('fileglob', 'k8s_modules.conf')}}"
    dest: /etc/modules-load.d/k8s.conf

- name: "load kernel modules"
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
   - overlay
   - br_netfilter

- name: "setup sysctl params"
  sysctl:
    name: "{{item}}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
    reload: yes
  with_items: 
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
  - net.ipv4.ip_forward

- name: setup docker repo
  block:
    - name: add docker repo key
      ansible.builtin.apt_key:
        short_id: 7EA0A9C3F273FCD8
        state: present
    - name: add docker repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: install docker
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin