---
# - debug: msg="{{lookup('fileglob', 'k8s.conf')}}"
- name: Set authorized key taken from file
  authorized_key:
    user: ds
    state: present
    key: "{{ lookup('file', 'id_rsa.pub') }}"

- name: "setup autoload kernel modules"
  copy:
    src: "{{lookup('fileglob', 'k8s_modules.conf')}}"
    dest: /etc/modules-load.d/k8s.conf

- name: "load kernel modules"
  modprobe:
    name: "{{item}}"
    state: present
  with_items:
   - overlay
   - br_netfilter

- name: "setup sysctl params"
  sysctl:
    name: "{{item}}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    state: present
    reload: yes
  with_items: 
  - net.bridge.bridge-nf-call-iptables
  - net.bridge.bridge-nf-call-ip6tables
  - net.ipv4.ip_forward

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"

- name: setup docker repo
  block:
    - name: add docker repo key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true
    - name: add docker repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: setup k8s repo
  block:
    - name: add k8s repo key
      get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /etc/apt/trusted.gpg.d/kubernetes.asc
        mode: '0644'
        force: true
    - name: add k8s repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main"
        state: present

- name: helm install
  block:
  - name: add helm repo key
    get_url:
      url: https://baltocdn.com/helm/signing.asc
      dest: /etc/apt/trusted.gpg.d/helm.asc
      mode: '0644'
      force: true
  - name: add helm repo
    ansible.builtin.apt_repository:
      repo: "deb https://baltocdn.com/helm/stable/debian/ all main"
      state: present

- name: remove 
  apt:
    pkg:
    - containerd.io
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-compose-plugin
    state: absent

- name: install need pkg
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - apt-transport-https
    - kubelet
    - kubeadm
    - kubectl
    - helm

- name: install containerd.io and runc
  block:
  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    ansible.builtin.unarchive:
      src:  https://github.com/containerd/containerd/releases/download/v1.7.2/containerd-1.7.2-linux-amd64.tar.gz
      dest: /usr/local/
      remote_src: yes
  - name: download runs
    get_url:
      url: https://github.com/opencontainers/runc/releases/download/v1.1.7/runc.amd64
      dest: /usr/local/sbin/runc
      mode: '0755'
  - name: install service containerd.io
    get_url:
      url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
      dest: /etc/systemd/system/containerd.service
  - name: generate containerd config
    shell: "containerd config default > /etc/containerd/config.toml"
  - shell: "sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml"
  - name: reload systemd
    systemd: 
      name: containerd
      daemon_reload: yes
      enabled: yes
      state: started

- name: hold k8s tools
  dpkg_selections:
    name: "{{item}}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl

