- template:
    src: "{{item}}"
    dest: "/tmp/{{item}}"
  loop: "{{ lookup('template', '{{ns}}/*.j2') }}"
- name: implement {{item}}
  shell: "kubectl apply -f /tmp/{{item|basename}}"
  loop: "{{ lookup('template', '{{ns}}/*.j2') }}"