- name: Create temporary  directory
  tempfile:
    state: directory
    suffix: manifests
  register: tmpdir

- name: "Generate manifest {{ns}}/{{item|basename}}"
  template:
    src: "{{ns}}/{{item|basename}}"
    dest: "{{tmpdir.path}}/{{item|basename|regex_replace('.j2$', '')}}"
  with_fileglob: "templates/{{ns}}/*.j2"
- name: "implement {{item|basename}}"
  shell: "kubectl apply --filename {{tmpdir.path}} --namespace {{ns}}"

- name: delete tmpdir
  file:
    path: "{{tmpdir.path}}"
    state: absent
  when: tmpdir.path is defined