# - template:
#     src: "{{ lookup('file', '{{item}}') }}"
#     dest: "/tmp/{{item}}"
#   loop: "{{ lookup('file', '{{ns}}/*.j2') }}"
# - name: implement {{item}}
#   shell: "kubectl apply -f /tmp/{{item}}"
#   loop: "{{ lookup('fileglob', '{{ns}}/*.j2') }}"
- debug: msg="{{item}} {{ns}}"
  loop: "{{ lookup('fileglob', '{{ns}}/*.j2') }}"