- block:
  - template:
      src: "{{ lookup('template', '{{ns}}/{{item|basename}}') }}"
      dest: "/tmp/{{item|basename}}"
  - name: implement {{item|basename}}
    shell: "kubectl apply -f /tmp/{{item|basename}}"
  with_fileglob: "templates/{{ns}}/*.j2"
