- template:
    src: "{{ lookup('file', '{{item}}') }}"
    dest: "/tmp/{{item}}"
  loop: "{{ lookup('fileglob', '{{ns}}/*.j2', wantlist=True) }}"
- name: implement {{item}}
  shell: "kubectl apply -f /tmp/{{item}}"
  loop: "{{ lookup('fileglob', '{{ns}}/*.j2', wantlist=True) }}"