- name: nginx setup
  block:
  - name: nginx install
    apt:
      pkg: nginx
  - name: nginx config setup
    template:
      src: "nginx.conf.j2"
      dest: /etc/nginx/nginx.conf
  - systemd: 
      name: nginx
      enabled: yes
      state: restarted

- name: reset
  shell: "kubeadm reset --dry-run"
  register: kubeadm_reset

- name: kubeadm init
  shell: "kubeadm init --upload-certs --token {{token}}  --pod-network-cidr {{pod_cidr}} --control-plane-endpoint master:443"
  run_once: true
  delegate_to: "{{groups.master.0}}"
  register: kubeadm_output

- name: join master node
  shell: "kubeadm join 127.0.0.1:443 --token {{token}} --discovery-token-unsafe-skip-ca-verification --control-plane"
  register: kubeadm_master_node
  when: inventory_hostname != groups.master.0

- debug: msg="{{kubeadm_output}}"
- debug: msg="{{kubeadm_reset}}"
- debug: msg="{{kubeadm_master_node}}"